[tasks.dev]
alias = "dev"
description = "Start web development server"
run = "pnpm dev"
depends = ["//:pnpm-install"]

[tasks.build]
description = "Build web"
run = "pnpm build"
depends = ["//:pnpm-install"]

[tasks.start]
description = "Start web"
run = "pnpm start"